#!/usr/bin/env python3
"""
Score one symbol's fragility from plain rows — no I/O, no HTTP, no file paths.

This is the only file that decides what "fragile" means, and it is deliberately the
one file with no idea where its input came from. Hand it a list of daily rows and it
hands back `AxisResult`s; whether those rows were paid for in credits, replayed from
`recorded/`, or generated by `synth_universe.py` is somebody else's problem. That
split is what lets the rule be tested at 10,200 test-days for free while the same
code path runs the demo.

    from fragility import score_price_volume, score_broker, score_catalyst

    axes = score_price_volume(rows, "2026-08-06")

The rule is from Nam & Skillicorn, arXiv 2301.11403: close and volume must *both*
exceed `mean + 2·SD` of the five trading days before the test date. Both, not either
— a price move without volume is a re-rating, and volume without price is churn.
`pstdev` and not `stdev`, because the five prior days are the whole population of the
baseline, not a sample drawn from one.

Every number an axis produces carries the `(endpoint, field)` it came from. The
renderer refuses to print a figure without that pair, so a citation invented here is
the only way a bare number could ever reach a user — which is why they are written
next to the arithmetic rather than at the call site.

    python3 src/fragility.py        # self-test: rule, edges, and the synth base rate

The self-test asserts the synth base rate is exactly 209 flags in 10,200 test-days.
That is the rule's false-positive rate under a null — `synth/` contains no planted
pump events — and it is pinned here so that a change to the rule shows up as a
failing number rather than as a quietly different demo.
"""
import glob
import json
import os
import statistics
import sys

BASELINE_DAYS = 5
SIGMA = 2.0

#: Flags reproduced from `synth/market/daily/` by `check_synth_base_rate`.
SYNTH_BASE_RATE = (209, 10200)


class AxisResult:
    """One fragility axis: a verdict, a sentence, and the citation behind it.

    `citation` is an `(endpoint, field)` pair, or a tuple of them when a figure is a
    join across two calls. `fragile` is None when the axis could not be evaluated —
    that is a third state, distinct from False, and the renderer prints it as
    "not fetched" rather than as a clean bill of health.
    """

    def __init__(self, name, fragile, detail, citation, values=None):
        self.name = name
        self.fragile = fragile
        self.detail = detail
        self.citation = citation
        self.values = values or {}

    @property
    def evaluated(self):
        return self.fragile is not None

    def __repr__(self):
        state = {True: "fragile", False: "clear", None: "not-fetched"}[self.fragile]
        return f"<AxisResult {self.name} {state}>"


def baseline(rows, field):
    """Mean and population SD of `field` over `rows`. Returns (None, None) if short."""
    if len(rows) < BASELINE_DAYS:
        return None, None
    values = [row[field] for row in rows]
    return statistics.mean(values), statistics.pstdev(values)


def sigmas_above(value, mean, sd):
    """How many SD `value` sits above `mean`. None when the baseline is flat or absent.

    A flat baseline is not zero-sigma, it is undefined: every value is infinitely many
    SD from a distribution with no width. Returning None keeps a suspended stock — five
    identical closes — from reading as an infinite anomaly on the sixth day.
    """
    if mean is None or not sd:
        return None
    return (value - mean) / sd


def score_price_volume(rows, test_date, endpoint="/v2/daily/{symbol}/"):
    """Price and volume anomaly against the five trading days before `test_date`.

    `rows` need not be sorted and may extend past `test_date`; the baseline is the five
    rows immediately preceding it in date order, and anything after it is ignored so
    that a longer capture cannot leak future data into the score.
    """
    ordered = sorted(rows, key=lambda r: r["date"])
    index = next((i for i, r in enumerate(ordered) if r["date"] == test_date), None)
    if index is None:
        missing = AxisResult("VOLUME", None, f"no row for {test_date}", (endpoint, "volume"))
        return [missing, AxisResult("PRICE", None, f"no row for {test_date}", (endpoint, "close"))]

    window = ordered[max(0, index - BASELINE_DAYS):index]
    day = ordered[index]
    axes = []
    for name, field in (("VOLUME", "volume"), ("PRICE", "close")):
        mean, sd = baseline(window, field)
        sigma = sigmas_above(day[field], mean, sd)
        if sigma is None:
            why = (f"only {len(window)} of {BASELINE_DAYS} baseline days before {test_date}"
                   if len(window) < BASELINE_DAYS else "baseline has no spread")
            axes.append(AxisResult(name, None, why, (endpoint, field)))
            continue
        unit = "shares" if field == "volume" else "Rp"
        shown = f"{day[field]:,} {unit}" if field == "volume" else f"{unit}{day[field]:,}"
        # Compared in the original units, as `mean + 2·SD`, not as a sigma ratio. The two
        # forms disagree on one of the 10,200 synthetic test-days purely through floating
        # point, and this is the form the literature states the rule in.
        axes.append(AxisResult(
            name,
            day[field] > mean + SIGMA * sd,
            f"{shown}, {sigma:.1f} SD {'above' if sigma >= 0 else 'below'} its own "
            f"{BASELINE_DAYS}-day baseline.",
            (endpoint, field),
            {"value": day[field], "sigma": sigma, "mean": mean, "sd": sd},
        ))
    return axes


def pump_flag(rows, test_date):
    """The literature rule itself: close AND volume both above mean + 2·SD."""
    axes = score_price_volume(rows, test_date)
    return all(axis.fragile for axis in axes)


def score_broker(top_buyers, cohort_by_code, endpoint="/v2/broker-summary/{symbol}/top/",
                 window=None):
    """Top-5 concentration of buy value, and how much of it is institutional or mixed.

    Re-specified from the research's retail-participation framing: only 5 of the 88
    brokers in `/v2/brokers/` carry the `retail` cohort, so a retail-dominance sentence
    is close to unproducible on real data. Institutional-vs-mixed dominance is the same
    signal read off a label that actually populates.

    `cohort_by_code` is the join to `/v2/brokers/`; an unknown code counts toward the
    concentration figure but not toward the cohort figure, so a partial join understates
    dominance rather than inventing it.

    `window` is the `(start, end)` the payload actually covers, and it is printed. The
    recorded ADRO summary spans 2026-06-07 to 2026-09-05 — about 90 days — so this axis
    does **not** move with the test date the way price and volume do. Saying so is the
    whole point of citing: a figure that sits next to "as of 2026-08-18" while silently
    describing a quarter is more misleading than no figure at all.
    """
    citation = ((endpoint, "buy_idr"), ("/v2/brokers/", "cohort"))
    if not top_buyers:
        return AxisResult("BROKER", None, "not fetched", citation)

    ranked = sorted(top_buyers, key=lambda b: b.get("buy_idr") or 0, reverse=True)
    total = sum(b.get("buy_idr") or 0 for b in ranked)
    if not total:
        return AxisResult("BROKER", None, "no buy value reported", citation)

    top5 = ranked[:5]
    share = sum(b.get("buy_idr") or 0 for b in top5) / total
    heavy = [b for b in top5
             if cohort_by_code.get(b.get("broker_code")) in ("institutional", "mixed")]
    span = f" over {window[0]}…{window[1]}" if window and all(window) else ""
    detail = (f"Top {len(top5)} buyers hold {share:.0%} of buy value{span}; "
              f"{len(heavy)} of {len(top5)} are institutional- or mixed-cohort.")
    if span:
        detail += " That window, not the test date — this axis does not move day to day."
    return AxisResult(
        "BROKER",
        share > 0.60,
        detail,
        citation,
        {"share": share, "heavy": len(heavy), "counted": len(top5)},
    )


def score_catalyst(articles, endpoint="/v2/news/"):
    """Absence of company news in the anomaly window.

    Inverted on purpose: news *present* is the unremarkable case, and silence around a
    2-SD move is the fragile one. `articles` is already windowed by the caller — this
    function does no date arithmetic, so it cannot disagree with the window the citation
    claims.
    """
    citation = (endpoint, "results")
    if articles is None:
        return AxisResult("CATALYST", None, "not fetched", citation)
    if not articles:
        return AxisResult("CATALYST", True, "No company news in the same window.", citation,
                          {"count": 0})
    return AxisResult("CATALYST", False,
                      f"{len(articles)} company news item(s) in the same window.",
                      citation, {"count": len(articles)})


def _synth_daily_dir():
    """Resolved here rather than imported from `sources`, deliberately.

    This module has no dependencies and no I/O outside its own self-test, which is what
    lets it be reasoned about as pure arithmetic. Importing the loader to save four lines
    would trade that away.
    """
    here = os.path.dirname(os.path.abspath(__file__))      # src/<idea>/
    root = os.path.dirname(os.path.dirname(here))          # the repository root
    return os.path.join(root, "research", "harness", "synth", "market", "daily")


def check_synth_base_rate():
    """Re-run the rule over every synthetic symbol and compare against SYNTH_BASE_RATE."""
    paths = sorted(glob.glob(os.path.join(_synth_daily_dir(), "*.json")))
    if not paths:
        return ["synth/market/daily/ is empty — run synth_universe.py"], 0

    flags = tested = hit = 0
    for path in paths:
        with open(path) as handle:
            rows = sorted(json.load(handle), key=lambda r: r["date"])
        symbol_flags = 0
        for i in range(BASELINE_DAYS, len(rows)):
            tested += 1
            if pump_flag(rows[i - BASELINE_DAYS:i + 1], rows[i]["date"]):
                symbol_flags += 1
        flags += symbol_flags
        hit += 1 if symbol_flags else 0

    expected_flags, expected_days = SYNTH_BASE_RATE
    failures = []
    if (flags, tested) != (expected_flags, expected_days):
        failures.append(f"expected {expected_flags}/{expected_days}, got {flags}/{tested}")
    print(f"        symbols={len(paths)} test-days={tested} flags={flags} "
          f"rate={flags / tested * 100:.4f}% symbols_with_flag={hit}")
    print("        synth has no planted pump events — this is a false-positive rate "
          "under a null, not a detection rate.")
    return failures, tested


def _rows(closes, volumes, start=1):
    return [{"date": f"2026-08-{start + i:02d}", "close": c, "volume": v}
            for i, (c, v) in enumerate(zip(closes, volumes))]


def check_rule():
    """The rule's own edges: both conditions, one condition, flat and short baselines."""
    failures = []
    calm_price = [100, 101, 99, 100, 100]
    calm_volume = [1000, 1100, 900, 1050, 950]

    both = _rows(calm_price + [200], calm_volume + [9000])
    if not pump_flag(both, "2026-08-06"):
        failures.append("close and volume both 2 SD up did not flag")

    price_only = _rows(calm_price + [200], calm_volume + [1000])
    if pump_flag(price_only, "2026-08-06"):
        failures.append("price move without volume flagged — the rule is AND, not OR")

    volume_only = _rows(calm_price + [100], calm_volume + [9000])
    if pump_flag(volume_only, "2026-08-06"):
        failures.append("volume without price move flagged — the rule is AND, not OR")

    dead = _rows([100] * 5 + [200], [1000] * 5 + [9000])
    axes = {a.name: a for a in score_price_volume(dead, "2026-08-06")}
    if axes["VOLUME"].fragile is not None or axes["PRICE"].fragile is not None:
        failures.append("a flat baseline scored instead of reporting not-evaluated")

    short = _rows([100, 101, 99], [1000, 1100, 900])
    if any(a.evaluated for a in score_price_volume(short, "2026-08-03")):
        failures.append("fewer than 5 baseline days scored instead of not-evaluated")

    absent = score_price_volume(both, "2026-09-30")
    if any(a.evaluated for a in absent):
        failures.append("a missing test date scored instead of not-evaluated")

    future = both + [{"date": "2026-08-07", "close": 1, "volume": 1}]
    if not pump_flag(future, "2026-08-06"):
        failures.append("a later row changed the score — future data leaked into the baseline")

    return failures, 7


def check_axes():
    """Broker and catalyst axes, including every not-evaluated path."""
    failures = []
    cohorts = {"YP": "institutional", "CC": "mixed", "PD": "retail", "XX": "unknown"}
    buyers = [{"broker_code": c, "buy_idr": v} for c, v in
              (("YP", 500), ("CC", 300), ("PD", 100), ("XX", 60), ("AA", 30), ("BB", 10))]

    broker = score_broker(buyers, cohorts)
    if not broker.fragile:
        failures.append(f"top-5 share {broker.values['share']:.2f} should be fragile above 0.60")
    if broker.values["heavy"] != 2:
        failures.append(f"expected 2 institutional/mixed in the top 5, got {broker.values['heavy']}")

    dated = score_broker(buyers, cohorts, window=("2026-06-07", "2026-09-05"))
    if "2026-06-07…2026-09-05" not in dated.detail:
        failures.append("a broker figure with a known window did not disclose it — "
                        "it reads as if it described the test date")
    if "over" in broker.detail:
        failures.append("a broker figure with no known window invented one")

    if score_broker([], cohorts).evaluated:
        failures.append("an empty broker list scored instead of reporting not fetched")
    if score_broker([{"broker_code": "YP", "buy_idr": 0}], cohorts).evaluated:
        failures.append("zero total buy value scored instead of reporting not fetched")
    if score_broker([{"broker_code": "YP"}], cohorts).evaluated:
        failures.append("a missing buy_idr key raised or scored — it must read with .get()")

    flat_book = [{"broker_code": c, "buy_idr": 100} for c in "ABCDEFGHIJ"]
    if score_broker(flat_book, cohorts).fragile:
        failures.append("an evenly spread book scored as concentrated")

    if not score_catalyst([]).fragile:
        failures.append("silence in the window should be the fragile case")
    if score_catalyst([{"title": "x"}]).fragile:
        failures.append("news present should not be fragile")
    if score_catalyst(None).evaluated:
        failures.append("None articles scored instead of reporting not fetched")

    return failures, 11


def main():
    results = [("rule edges", *check_rule()),
               ("axis scoring", *check_axes()),
               ("synth base rate", *check_synth_base_rate())]

    failed = 0
    for name, failures, checked in results:
        mark = "PASS" if not failures else "FAIL"
        print(f"{mark}  {name:16} {checked} checked, {len(failures)} failed")
        for failure in failures:
            print(f"        {failure}")
        failed += len(failures)

    print("\nscorer behaves as specified" if not failed
          else f"\n{failed} scorer divergence(s)")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
